Using MSVC typeof(this) workaround on all MSVC version not just 8.0 because trunk regression tests shown this MSVC bug (which raises error C2355) was not fixed in 9 and later version as originally thought.
[SVN r77336]